### ISSUE TITLE
Update hugo command to work with gitpod host.

### ISSUE THREAD

**Issue by iveptawebadmin** [gitpod-io/template-hugo#1]
https://github.com/gitpod-io/template-hugo/blob/c616717538a9bf0eb3bee9264de2de83fcefb7a4/.gitpod.yml#L6

Should be:

`hugo server -D --baseUrl $(gp url 1313) --appendPort=false`

**Comment by pawlean** [comment]
Awesome find, thanks @iveptawebadmin! Want to raise a PR?

**Comment by iveptawebadmin** [comment]
> Awesome find, thanks @iveptawebadmin! Want to raise a PR?

Not for that small change, sorry to not play well with others on this one.

**Comment by zivbk1** [comment]
I decided to play nice and added a PR. :D

**Comment by pawlean** [comment]
No problem at all @iveptawebadmin... I didn't understand your comment, apologises if I offended, mostly wanted to enable others to contribute 😂

Thank you for raising a PR @zivbk1!

**Comment by zivbk1** [comment]
@pawlean I am both @iveptawebadmin and @zivbk1 :D No offense taken, I was just being lazy in the beginning.
